# Generated by Django 4.1.4 on 2023-01-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_comments_options_alter_posts_options_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like_value',
            field=models.BooleanField(default=False),
        ),
    ]
